version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=f1db
    ports:
      - "3307:3306"
  app:
    depends_on:
      - mysqldb
    build: .
    restart: on-failure
    ports:
      - "8080:8080"